### PR TITLE
Prepare release 0.4.0

### PR DESCRIPTION
**Pull request by tsauerwein**
I wasn't sure about the version number. @elemoine, let me know if you want the version to be 0.3.1 or 0.4.0.

### CODE REVIEW

**Comment by elemoine** [comment]
It does not matter too much, but I'd go with 0.4, given that you added a new feature.

**Comment by tsauerwein** [comment]
Ok, no problem. I updated the version.

**Comment by elemoine** [comment]
Feel free to merge this and push the 0.4 tag.

**Comment by tsauerwein** [comment]
It looks like it worked: https://pypi.python.org/pypi/GeoAlchemy2/0.4.0

Can I ask you to do the last step of the release procedure:

> Go to http://readthedocs.org/dashboard/geoalchemy-2/edit/ and set "Default version" to x.y.

Thanks!

**Comment by elemoine** [comment]
> Can I ask you to do the last step of the release procedure

Done.

If you have a username on rtd I could give you admin rights for GeoAlchemy.

**Pull request merged**
