### PR TITLE
Get prepared for 0.6.1

### PR DESCRIPTION
**Pull request by elemoine**

### CODE REVIEW

**Comment by elemoine** [comment]
@adrien-berchet-forcity, @SergeBouchut 0.6.1 will be on pypi very soon.

**Comment by elemoine** [comment]
See https://pypi.org/project/GeoAlchemy2/0.6.1.

**Comment by adrien-berchet-forcity** [comment]
Thank you very much for this quick release! We will test that very soon :)

**Comment by sbouchut** [comment]
Thanks! :)

**Comment by elemoine** [comment]
I added you to the contributors list. See https://geoalchemy-2.readthedocs.io/en/latest/. Welcome!

**Comment by adrien-berchet-forcity** [comment]
Oh thanks! :blush:

**Pull request merged**
