### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by tigerfoot**
Fix issue #96 
Based on previous pr #86 
Add specific test

### CODE REVIEW

**Comment by Turbo87** [comment]
looks good to me. @elemoine any comments?

**Comment by tigerfoot** [comment]
Ping?

**Comment by Turbo87** [comment]
I'll merge since nobody seems to veto this...

**Comment by tigerfoot** [comment]
On Monday 18 May 2015 06.59:23 Tobias Bieniek wrote:
> Merged #99.
> 
Thanks
-- 

Bruno Friedmann 
Ioda-Net Sàrl www.ioda-net.ch

**Comment by elemoine** [comment]
Thanks again!

**Pull request merged**
