### PR TITLE
Fix: Default SRID is bypassed when using floating point coordinates.

### PR DESCRIPTION
**Pull request by aballet**
### Description
This is a very simple one-character fix. Since v0.15.0, the new `SPLIT_WKT_PATTERN` regex did not account for floating point coordinates. The match() method returns None, and the `default_srid` is never applied in `format_geom_type()`.

How do you suggest testing for this? Current functional tests do not have any floating point, so I could add one there? Or make them all floats instead of integers?

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- [ ] Please include: `Fixes: #<issue number>` in the description if it solves an existing issue
	  (which must include a complete example of the issue).
	- [x] Please include tests that fail with the `main` branch and pass with the provided fix.
- [ ] A new feature implementation or update an existing feature
	- [ ] Please include: `Fixes: #<issue number>` in the description if it solves an existing issue
	  (which must include a complete example of the feature).
	- [ ] Please include tests that cover every lines of the new/updated feature.
	- [ ] Please update the documentation to describe the new/updated feature.

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Hi @aballet 
You're absolutely right, thank you very much for spotting this issue and sorry about this stupid miss...
I think it makes sense to update the tests to include floating point numbers, especially in `test_functional.py::TestInsertionCore::test_insert_all_geom_types`. You can add a `pytest.mark.parametrize` to test with only integers or with floating points.

**Comment by adrien-berchet** [comment]
I updated the test in https://github.com/aballet/geoalchemy2/pull/1/ so you can merge and then I'll merge this PR.

**Comment by aballet** [comment]
Ah, I see that I forgot to escape the dot myself, thank you!
I merged your code to include the tests.

**Comment by adrien-berchet** [comment]
Thanks for this work @aballet !
I'm going to push a new release.

**Comment by adrien-berchet** [comment]
The new release is available: https://pypi.org/project/GeoAlchemy2/0.15.1/
I hope it will solve your issue @aballet 
Anyway, thanks again for this PR @aballet !

**Pull request merged**
