### PR TITLE
Support geometry column with no typmod

### PR DESCRIPTION
**Pull request by elemoine**
Fixes https://github.com/geoalchemy/geoalchemy2/issues/158.

### CODE REVIEW

**Comment by elemoine** [comment]
@tomkradilis, do you want to test that?

**Comment by tomkralidis** [comment]
@elemoine running https://gist.github.com/tomkralidis/3f11c88969e0c2d9d7a213827d75ab56#file-test_zgeom-fix-py with the fix in this PR yields the below:

```
/home/tkralidi/woudc-data-registry/lib/python3.4/site-packages/geoalchemy2/types.py:116: UserWarning: srid not enforced when geometry_type is None
  warnings.warn('srid not enforced when geometry_type is None')
Generating models
2017-07-31 10:43:58,784 INFO sqlalchemy.engine.base.Engine select version()
2017-07-31 10:43:58,785 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,791 INFO sqlalchemy.engine.base.Engine select current_schema()
2017-07-31 10:43:58,792 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,797 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2017-07-31 10:43:58,797 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,800 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2017-07-31 10:43:58,801 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,803 INFO sqlalchemy.engine.base.Engine show standard_conforming_strings
2017-07-31 10:43:58,803 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,811 INFO sqlalchemy.engine.base.Engine
CREATE TABLE data_record_foo (
        identifier SERIAL NOT NULL,
        PRIMARY KEY (identifier)
)


2017-07-31 10:43:58,811 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,832 INFO sqlalchemy.engine.base.Engine COMMIT
2017-07-31 10:43:58,840 INFO sqlalchemy.engine.base.Engine SELECT AddGeometryColumn(%(AddGeometryColumn_2)s, %(AddGeometryColumn_3)s, %(AddGeometryColumn_4)s, %(AddGeometryColumn_5)s, NULL, %(AddGeometryColumn_6)s, %(AddGeometryColumn_7)s) AS "AddGeometryColumn_1"
2017-07-31 10:43:58,840 INFO sqlalchemy.engine.base.Engine {'AddGeometryColumn_4': 'location', 'AddGeometryColumn_6': 2, 'AddGeometryColumn_3': 'data_record_foo', 'AddGeometryColumn_5': 4326, 'AddGeometryColumn_2': 'public', 'AddGeometryColumn_7': False}
2017-07-31 10:43:58,844 INFO sqlalchemy.engine.base.Engine COMMIT
2017-07-31 10:43:58,845 INFO sqlalchemy.engine.base.Engine CREATE INDEX "idx_data_record_foo_location" ON "public"."data_record_foo" USING GIST ("location")
2017-07-31 10:43:58,845 INFO sqlalchemy.engine.base.Engine {}
2017-07-31 10:43:58,848 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "/home/tkralidi/woudc-data-registry/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/tkralidi/woudc-data-registry/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "location" does not exist
```

**Comment by elemoine** [comment]
You no longer need `management=True` and `use_typmod=False`. You also want to remove `srid=4326`. With `geometry_type=None` no typmod is applied.

**Comment by tomkralidis** [comment]
Thanks @elemoine; works,

**Comment by elemoine** [comment]
Cool. Thanks for testing.

Coverage decrease is minor, I'll merge this if there's no negative feedback.

**Comment by tomkralidis** [comment]
+1

**Comment by elemoine** [comment]
Thanks @tsauerwein. I just added in the doc that `geometry_type=None` is not compatible with `management=True`. Will merge when Travis has finished runnning.

**Pull request merged**
