### PR TITLE
create debian packaging (#159)

### PR DESCRIPTION
**Pull request by tomkralidis**

### CODE REVIEW

**Comment by elemoine** [comment]
Thanks. How can I build the package?

**Comment by tomkralidis** [comment]
@elemoine I've added Debian building to travis.

**Comment by elemoine** [comment]
Build is green now, do you want to squash your commits?

**Comment by tomkralidis** [comment]
@elemoine not yet.  You will in `after_success` the Debian package build is failing.  I've marked this PR **WIP** until I fix.

**Comment by elemoine** [comment]
Sure. Please tell me when you need this reviewed.

**Comment by elemoine** [comment]
@tomkralidis do you plan to work on this again in the future? Or should we close it? Thanks.

**Comment by tomkralidis** [comment]
@elemoine I've rebased to current master.  Looks like things pass now (travis is unchanged) to be squashed/merged.

**Comment by elemoine** [comment]
I've realized that @EdwardBetts already packaged GeoAlchemy2 for Debian. See https://salsa.debian.org/python-team/modules/geoalchemy2 and https://packages.debian.org/sid/python3-geoalchemy2. Thank you very much @EdwardBetts!

@tomkralidis what do you think? Do you need more than what @EdwardBetts did?

**Comment by tomkralidis** [comment]
Ah great! We can use that and close this PR then.

**Pull request closed without merging**
