### PR TITLE
Deserialization for WKB

### PR DESCRIPTION
**Pull request by Giszmo**
@lweberk created issue https://github.com/geoalchemy/geoalchemy2/issues/51
and we've been working on resolving it on our end. This merge request shares our findings. It adds a property to WKBElement to access WKB as a python-native tuple.

For example on my table with a field of type Polygon, initializing the polygon with

``` python
  lake.geom = POLYGON((88.555555555 88.555555555,89.555555555 88.555555555,89.555555555 89.555555555,88.555555555 88.555555555))
```

(produces this well known binary:

```
  b'0103000000010000000400000083f5e2388e23564083f5e2388e23564083f5e2388e63564083f5e2388e23564083f5e2388e63564083f5e2388e63564083f5e2388e23564083f5e2388e235640'
```

) and when querying lake.geom from the db I get this geom.tuple:

``` python
Polygon(wkb_id=3, rings=[LineString(wkb_id=2, points=[Point(wkb_id=1, x=88.555555555, y=88.555555555), Point(wkb_id=1, x=89.555555555, y=88.555555555), Point(wkb_id=1, x=89.555555555, y=89.555555555), Point(wkb_id=1, x=88.555555555, y=88.555555555)])])
```

A way to re-serialize the tuple exists in wkb.py but is not exposed to WKBElement yet.

This code is not ready for productive use in general geoalchemy2 applications but will most likely not get extended by us neither if there is no interest by the community, as it serves our needs as is.

### CODE REVIEW

**Comment by elemoine** [comment]
I am closing this due to lack of activity. Feel free to create a new issue or PR if you'd like to discuss this again. Thanks.

**Comment by lweberk** [comment]
It neither got any discussion from the maintainers nor a merge. I'm ok with the drop, since we moved on anyways.

**Comment by elemoine** [comment]
> I'm ok with the drop, since we moved on anyways.

Not using GeoAlchemy anywore?

**Comment by lweberk** [comment]
Correct. The application just needed to save latitude and longitude. Since the original need for spacial indexing as not yet been pressing, we moved away from geoalchemy. Who knows, maybe we will return to it someday ;).

Either way, wish you best of success with the project.

**Comment by elemoine** [comment]
> Either way, wish you best of success with the project.

Thanks. The activity is low these days, but GeoAlchemy seems to work for people.

**Comment by lukas-gitl** [comment]
@elemoine It just works, that's why the activity is low ;)

**Pull request closed without merging**
