### PR TITLE
Indicate in setup.py that geoalchemy2 works with Python3

### PR DESCRIPTION
**Pull request by willemarcel**
* Indicate in setup.py that geoalchemy2 works with Python3
* Add testenv to python3.5
* Improve test documentation

### CODE REVIEW

**Comment by Turbo87** [comment]
@willemarcel Thanks for the pull request. Would you mind adjusting the `.travis.yml` file too so that Python 3.5 is also tested?

**Comment by willemarcel** [comment]
@Turbo87 done!

**Comment by Turbo87** [comment]
hmm, somehow this doesn't seem to work although TravisCI seems to support Python 3.5 by now...

**Comment by willemarcel** [comment]
it's strange... Do you prefer I remove the python 3.5 tests?

**Comment by Turbo87** [comment]
that or make it work properly, but I have to admit that I wouldn't know how exactly to fix this either

**Comment by willemarcel** [comment]
I fixed the python3.5 tests that were failing on travis.ci following this tip https://github.com/travis-ci/travis-ci/issues/4794#issuecomment-143758799

**Comment by Turbo87** [comment]
awesome, thanks!

**Comment by elemoine** [comment]
This PR somehow broke the Read the Docs build, or revealed that our the Read the Docs build is broken (due to external reasons). See https://github.com/geoalchemy/geoalchemy2/issues/113. I'll look into it.

**Pull request merged**
