### PR TITLE
Adds ability to pickle SpatialElements

### PR DESCRIPTION
**Pull request by katerina7479**
I need the ability to pickle WKBElements for some multiprocessing work I'm doing. Would really appreciate this functionality being included in your project!

### CODE REVIEW

**Comment by elemoine** [comment]
It looks to me that `SpatialElement_`s are already pickable. Can you please provide a test-case demonstrating that they are not. Thank you.

**Comment by katerina7479** [comment]
Well, I am using multiprocess, in conjunction with sqlalchemy with Geography locations. Specifically the WKBElement needs to be serializeable and pickleable, and it is not. I put the methods on the base class though. It's the whole system working together, and I can't really give you a short example, except to say it works on my fork, and not on your package.

**Comment by elemoine** [comment]
Here is a script that works for me:

```py
import pickle
from geoalchemy2 import WKBElement


e = WKBElement(b'\x01\x02', srid=4326)
assert(e.desc == '0102')
assert(e.srid == 4326)

p = pickle.dumps(e)

n = pickle.loads(p)
assert(n.desc == e.desc)
assert(n.data == e.data)
assert(n.srid == e.srid)
```

**Comment by elemoine** [comment]
@katerina7479 curious to know if that finally worked for you…

**Pull request closed without merging**
