### PR TITLE
Add SpatiaLite support

### PR DESCRIPTION
**Pull request by elemoine**
This PR adds SpatialLite support. This is WIP at this point. The code basically works, but I need to do more testing, add more automated tests, and better docs.

### CODE REVIEW

**Comment by achapkowski** [comment]
Let’s add this!

**Comment by elemoine** [comment]
> Let’s add this!

Thank you for you support :) I still need to add a few more tests. My plan is to complete this before the end of June.

**Comment by achapkowski** [comment]
@elemoine True, do you plan on adding Windows OS support as well?

**Comment by elemoine** [comment]
> @elemoine True, do you plan on adding Windows OS support as well?

It should work on Windows, although I haven't tested it.

**Comment by elemoine** [comment]
I have removed the WIP flag. Reviews are welcome. My plan is to merge this before the end of June. Thank you!

**Comment by elemoine** [comment]
Any objection for merging this? I'll merge this later today if I there's no objection. Thank you!

**Comment by elemoine** [comment]
I'm merging this. Post-merge comments are still welcome!

**Pull request merged**
