### PR TITLE
Simplify and fix tests

### PR DESCRIPTION
**Pull request by elemoine**
The current tests do not pass with SQLA 1.1.2 (the most recent stable version). This PR makes the tests compatible with SQLA 1.1.2, and removes the execution of the tests on SQLA 0.8 and 0.9 in the CI. The execution of the tests on Python 2.6 is also removed.

### CODE REVIEW

**Comment by elemoine** [comment]
I'll merge this soon if there's no push-back.

**Comment by sbrunner** [comment]
Looks good, there is just some coverage error :-)

**Comment by elemoine** [comment]
> Looks good, there is just some coverage error :-)

This is minor. It's related to SQLA < 0.9 not being tested anymore. See https://coveralls.io/builds/8461743/source?filename=geoalchemy2%2Felements.py for example.

**Comment by sbrunner** [comment]
Yes :-)
I don't like a "normal" test failed, than I think that you should add some `pragma: no cover` or change the coveralls config to make the test pass :-)

**Comment by sbrunner** [comment]
Thanks @elemoine  :-)

**Pull request merged**
