### PR TITLE
Document the use of spatial functions in primaryjoin conditions

### LINKED ISSUE #220: How to do a spacial join?
Consider two objects: points and polygons.

I would like to create a relationship on the point object so that I can see which polygons (if any), the point is contained within.

Writing a query for this in raw SQL is pretty straightforward:

```sql
SELECT *
FROM points
FULL JOIN polygons ON ST_Within(points.the_point, polygons.the_area)
```

How would I represent this relationship in geoalchemy?

### PR DESCRIPTION
**Pull request by elemoine**
Fixes #220.

### CODE REVIEW

**Comment by elemoine** [comment]
I'll merge this this afternoon or tomorrow if I there's no feedback.

**Comment by troyswanson** [comment]
I wonder if it would be helpful to provide an example the other way as well, to show the relationship from the treasure's perspective.

In other words, "what lake does this treasure live in?" vs "what treasure lives in this lake?"

Also, it might be helpful to discuss (very basic) lazy/eager loading strategies. With lazy loading, Iterating on the lake response and accessing the treasure attribute would get very expensive, since it would emit a new SQL query for every lake. Eager loading would eliminate that expense.

Related docs: https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#joined-eager-loading

**Comment by elemoine** [comment]
I can add a backref to the relationship and a sentence to explain what it does.

I can also mention that the relationship is configured with the default `lazy="select"` strategy, with a link to the appropriate SQLA doc section.

And I think I'll stop there, to avoid rewriting the SQLA docs :)

Thanks for your suggestions!

**Comment by elemoine** [comment]
I added more information. Will merge when the CI process is finished.

**Pull request merged**
