### PR TITLE
Change WKTElement to read SRID from the EWKT string.

### PR DESCRIPTION
**Pull request by adrien-berchet-forcity**
Make WKTElement behaviour consistent with the WKBElement one introduced in #209.

### CODE REVIEW

**Comment by elemoine** [comment]
Not sure I agree with that change but I'll have a closer look.

**Comment by elemoine** [comment]
I was hesitant because I think there may be a problem [here](https://github.com/geoalchemy/geoalchemy2/blob/master/geoalchemy2/types.py#L146), where that line is not compatible with extended WKTElement objects. But this problem exists independently from your change actually.

**Comment by elemoine** [comment]
We need to add more tests to TestGeometry.

**Comment by adrien-berchet-forcity** [comment]
Ok I see your point. I updated a test and proposed a simple fix in bind_processor() to point the issue. But it probably could be done in a better way.

But maybe you prefer keeping the old behavior?

**Comment by elemoine** [comment]
I just want to make sure that we're not breaking backward compatibility. It looks like we're not. Do you agree?

**Comment by elemoine** [comment]
I made changes directly to your branch. Happy to merge it if you agree. Thanks!

**Comment by adrien-berchet-forcity** [comment]
I also think we don't break anything with this new version. Thank you for your last updates.

**Pull request merged**
