### PR TITLE
Prepare release 0.4.2

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by elemoine** [comment]
I will merge this and push the tag this afternoon. (Pushing the tag automatically publishes a new version on pypi.)

**Comment by fredj** [comment]
thanks !

**Comment by elemoine** [comment]
Done: https://pypi.python.org/pypi/GeoAlchemy2/0.4.2.

**Comment by fredj** [comment]
tested and working, thanks again

**Pull request merged**
